#!/bin/sh
_DIR=$( cd -- "$( dirname -- "${0}" )" &> /dev/null && pwd )

apk add git tmux neovim lf openssh-client python3 py3-pip bash curl helix helix-tree-sitter-vendor

export PATH=$PATH:/root/.local/bin

curl -s https://ohmyposh.dev/install.sh | bash -s
cp $_DIR/spaceship-st.omp.json /root/.cache/oh-my-posh/themes/
oh-my-posh init bash --config /root/.cache/oh-my-posh/themes/spaceship-st.omp.json

cp /etc/passwd /etc/passwd.bak

cat /etc/passwd | sed -E "s|^root(.*)/bin/sh|root\1/bin/bash|" >/etc/passwd.new

diff /etc/passwd.new /etc/passwd.bak

read -p "apply? [y/n] " ANSW; [ $ANSW = "y" ] && cp /etc/passwd.new /etc/passwd

rm -f /etc/passwd.new /etc/passwd.bak

read -p "Username: " USERNM; echo; scp $USERNM@s2.lab18.net:~/.ssh/id_rsa ~/.ssh/

cp $_DIR/profile.ipad.sh ~/.profile

cp $_DIR/config.toml ~/.config/helix/config.toml

mkdir -p ~/.config/lf

cp $_DIR/lfrc ~/.config/lf/lfrc
