#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = false
    enable_vimfiler_gitstatus = true
    # file manager plugins supported in SpaceVim:
    # - vimfiler (default)
    # - nerdtree
    # - defx
    filemanager = "vimfiler"
    enable_vimfiler_gitstatus = 1
    enable_vimfiler_welcome = 0
    # custom inits
    bootstrap_before = "stinger#set_maps"

# Enable autecomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
 name = 'VersionControl'

[[layers]]
  name = "checkers"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#scala"

[[layers]]
  name = "lang#rust"
  recommended-style = true

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "fzf"

[[layers]]
  name = "tags"

[[layers]]
  name = "git"

[[layers]]
  name = "colorscheme"

[[custom_plugins]]
  name = "junegunn/seoul256.vim"
  merged = 0
 
#[[custom_plugins]]
#  name = "tpope/vim-fugitive"
#  merged = 0
# 
#[[custom_plugins]]
#[[custom_plugins]]
#  name = "kristijanhusak/defx-git"
# 
